import { createInstagramPost, findInstagramChannel, getScheduledPosts, isBufferConfigured } from "../../../../lib/buffer";
export const dynamic="force-dynamic";
const base="https://www.orangesoft.uk/api/orangesoft-social-card?card=";
const posts=[
{dueAt:"2026-09-17T17:30:00.000Z",imageUrl:base+"research",altText:"OrangeSoft projects across software computing and digital products",text:`OrangeSoft develops technology across software, computing and digital products.\n\nOur current projects include:\n\nOrangeSoft OS — an operating system built by OrangeSoft, exploring our own approach to the desktop and computing environment.\n\nBlueprint — our own programming language, designed around a different way of expressing commands, logic and software instructions.\n\nStoryLingo — a multilingual reading platform where stories become an interactive way to read, explore vocabulary and practise languages.\n\nFollow OrangeSoft to watch these projects develop, see what we’re working on behind the scenes, and be among the first to try what we release next.\n\n#OrangeSoft #Technology #Programming #ProgrammingLanguage #OperatingSystems #Software #StoryLingo #Blueprint`},
{dueAt:"2026-09-19T12:00:00.000Z",imageUrl:base+"blueprint",altText:"Blueprint programming language by OrangeSoft",text:`Blueprint is our own programming language.\n\nIt is designed around a different way of expressing commands, logic and software instructions.\n\nFollow its development → orangesoft.uk/blueprint\n\n#OrangeSoft #Blueprint #Programming #ProgrammingLanguage #SoftwareDevelopment`},
{dueAt:"2026-09-21T17:30:00.000Z",imageUrl:base+"storylingo",altText:"StoryLingo multilingual reading platform by OrangeSoft",text:`StoryLingo turns stories into an interactive way to practise languages.\n\nRead in multiple languages, explore vocabulary and practise what you learn as you move through each story.\n\nExplore → storylingo.uk\n\n#OrangeSoft #StoryLingo #LanguageLearning #Reading #Technology`},
{dueAt:"2026-09-22T12:00:00.000Z",imageUrl:base+"os",altText:"OrangeSoft OS operating system project",text:`OrangeSoft OS is our operating system project.\n\nWe’re exploring our own approach to the desktop and computing environment as the system develops.\n\nFollow the project → orangesoft.uk\n\n#OrangeSoft #OperatingSystems #Software #Computing #Technology`}
];
export async function GET(){if(!isBufferConfigured())return Response.json({ok:false,message:"BUFFER_API_KEY is not configured."},{status:503});try{const match=await findInstagramChannel("orangesoft.uk");if(!match)return Response.json({ok:false,message:"Could not find @orangesoft.uk in Buffer."},{status:404});const existing=await getScheduledPosts(match.organization.id,match.channel.id);const created=[];for(const item of posts){if(existing.some(p=>p.text===item.text))continue;created.push(await createInstagramPost({channelId:match.channel.id,...item}));}return Response.json({ok:true,existing:existing.length,created});}catch(error){return Response.json({ok:false,message:error instanceof Error?error.message:"Weekly queue failed."},{status:502});}}