import { createInstagramPost, findInstagramChannel, getScheduledPosts, isBufferConfigured } from "../../../../lib/buffer";
export const dynamic="force-dynamic";
const base="https://www.orangesoft.uk/api/orangesoft-social-card?card=";
const posts=[
{dueAt:"2026-09-17T17:30:00.000Z",imageUrl:base+"research",altText:"OrangeSoft research card about artificial intelligence and advanced computing",text:`What are we building at OrangeSoft?\n\nA British technology research company focused on artificial intelligence and advanced computing. Our work spans AI models and reasoning systems, experimental products, and operating-systems research.\n\nResearch what comes next → orangesoft.uk\n\n#ai #artificialintelligence #technology #innovation #aitech`},
{dueAt:"2026-09-19T12:00:00.000Z",imageUrl:base+"blueprint",altText:"Blueprint artificial intelligence research project by OrangeSoft",text:`Blueprint is our AI research project.\n\nWe’re using it to explore reasoning, experimentation, multilingual interaction and new AI capabilities — not as a finished answer, but as an environment for asking better technical questions.\n\nExplore Blueprint → orangesoft.uk/blueprint\n\n#ai #artificialintelligence #machinelearning #aitech #aifuture`},
{dueAt:"2026-09-21T17:30:00.000Z",imageUrl:base+"storylingo",altText:"StoryLingo multilingual language-learning product by OrangeSoft",text:`Research becomes more useful when it turns into something people can use.\n\nStoryLingo is an OrangeSoft product built around multilingual reading: stories, interactive vocabulary, writing practice, pronunciation and audio in one reading environment.\n\nExplore → storylingo.uk\n\n#languagelearning #edtech #technology #softwaredevelopment #innovation`},
{dueAt:"2026-09-22T12:00:00.000Z",imageUrl:base+"os",altText:"OrangeSoft OS operating systems research card",text:`AI isn’t the whole research agenda.\n\nOrangeSoft OS is an operating system under development as part of our work on advanced and general-purpose computing. It sits alongside our AI research rather than being an AI-oriented operating system.\n\nMore → orangesoft.uk\n\n#operatingsystem #systemdesign #softwaredevelopment #engineering #technology`}
];
export async function GET(){if(!isBufferConfigured())return Response.json({ok:false,message:"BUFFER_API_KEY is not configured."},{status:503});try{const match=await findInstagramChannel("orangesoft.uk");if(!match)return Response.json({ok:false,message:"Could not find @orangesoft.uk in Buffer."},{status:404});const existing=await getScheduledPosts(match.organization.id,match.channel.id);const created=[];for(const item of posts){if(existing.some(p=>p.text===item.text))continue;created.push(await createInstagramPost({channelId:match.channel.id,...item}));}return Response.json({ok:true,existing:existing.length,created});}catch(error){return Response.json({ok:false,message:error instanceof Error?error.message:"Weekly queue failed."},{status:502});}}